name: WORKFLOW_TEST

on:
  workflow_dispatch:

# Please replace SUPER_SECRET with Your secret name.
# Secret will be encrypted with RSA Public key and base64 encoded.
# You need to have RSA Private Key to decrypt output.
# If You want to use this workflow, please generate Your RSA pair and replace Public key used below.
# Please pay attention to runs-on -> this example uses ubuntu, but sometimes You need to use a different runner.

# Secret can be decrypted by this command:
# cat encrypted.txt | base64 -d | openssl pkeyutl -decrypt -inkey rsa_key.pri
env:
  password: ${{ secrets.SUPER_SECRET }}


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Store the secret in the tmp file
        run: echo "${{ env.password }}" >> output.txt

      - name: Verify length
        run: wc -c output.txt

      - name: Store the pub certificate
        run: echo -e "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmeT1VMIx5khLBC2GBheU\nCBwRvEUobS235MRuQboRL6W+Mkq2qLXNhBhQ0wAS7tjHzZW1hQNV18ZeqC8uJuC+\n+KC2rEzNSzbgj1DCBHTgAJCuOiomIi0h1pN6gzh/dWn++0t7Co9LTVoG2YQKtFY9\ntSFiIR0Apj3EwHbcRiBlJkmWjweges/ZsOxraxAfctXyl/Q5TX5eK/QRHw0Gyh0s\nKVKc9ramSzulF7NNbg+DQQUovphS/5KCaVzMXAJqGlUCXGjEqKOMGXvny0yHiJqa\nt2iBua5SWNyXt6CWOKdb9dp2Db7XivvrZYN0Xcdx4JyyWKRg5t6eDUiY/UJvOfT2\nzwIDAQAB\n-----END PUBLIC KEY-----" > rsa_key.pub

      - name: Encrypt the file with PUB key
        run: openssl pkeyutl -encrypt -pubin -inkey rsa_key.pub -in output.txt | base64 > encrypted.txt

      - name: Read the content
        run: cat encrypted.txt
